spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tab_db
    username: postgres
    password: bestdrifterNA!23
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect